/*
 * VMware Workstation REST API
 *
 * vmrest 1.3.0 build-20800274
 *
 * API version: 1.3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Information about a NIC
type NicIpStack struct {
	// Mac address of the interface
	Mac string `json:"mac"`
	// IP address(es) of the interface (CIDR)
	Ip []string `json:"ip,omitempty"`
	// DNS configuration of the interface
	Dns *DnsConfig `json:"dns,omitempty"`
	// WINS configuration of the interface
	Wins *WinsConfig `json:"wins,omitempty"`
	// DHCPv4 configuration of the interface
	Dhcp4 *DhcpConfig `json:"dhcp4,omitempty"`
	// DHCPv6 configuration of the interface
	Dhcp6 *DhcpConfig `json:"dhcp6,omitempty"`
}
