/*
 * VMware Workstation REST API
 *
 * vmrest 1.3.0 build-20800274
 *
 * API version: 1.3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Routing entry
type RouteEntry struct {
	Dest      string `json:"dest"`
	Prefix    int    `json:"prefix"`
	Nexthop   string `json:"nexthop,omitempty"`
	Interface int    `json:"interface"`
	Type      int    `json:"type"`
	Metric    int    `json:"metric"`
}
